create table public.posts (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text null,
  date date null,
  cover text null,
  content text null,
  tag json null,
  slug text null,
  author uuid null,
  constraint blog_pkey primary key (id),
  constraint posts_author_fkey foreign KEY (author) references auth.users (id)
) TABLESPACE pg_default;