-- Improved schema for posts table with proper constraints
DROP TABLE IF EXISTS public.posts CASCADE;

CREATE TABLE public.posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    title text NOT NULL,
    slug text NOT NULL,
    content text NOT NULL,
    date date NULL,
    cover text NULL,
    tag json NULL,
    author uuid NULL REFERENCES auth.users(id) ON DELETE SET NULL,
    
    -- Constraints
    CONSTRAINT posts_pkey PRIMARY KEY (id),
    CONSTRAINT posts_slug_unique UNIQUE (slug),
    CONSTRAINT posts_title_not_empty CHECK (length(trim(title)) > 0),
    CONSTRAINT posts_content_not_empty CHECK (length(trim(content)) > 0),
    CONSTRAINT posts_slug_format CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
) TABLESPACE pg_default;

-- Create indexes for better performance
CREATE INDEX posts_created_at_idx ON public.posts (created_at DESC);
CREATE INDEX posts_author_idx ON public.posts (author);
CREATE INDEX posts_title_gin_idx ON public.posts USING gin (to_tsvector('english', title));
CREATE INDEX posts_content_gin_idx ON public.posts USING gin (to_tsvector('english', content));
CREATE INDEX posts_tag_gin_idx ON public.posts USING gin (tag);

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger to auto-update updated_at
CREATE TRIGGER update_posts_updated_at 
    BEFORE UPDATE ON public.posts 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Enable Row Level Security (RLS)
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone can read published posts
CREATE POLICY "Posts are viewable by everyone" ON public.posts
    FOR SELECT USING (true);

-- Policy: Users can insert their own posts
CREATE POLICY "Users can create posts" ON public.posts
    FOR INSERT WITH CHECK (auth.uid() = author);

-- Policy: Users can update their own posts
CREATE POLICY "Users can update own posts" ON public.posts
    FOR UPDATE USING (auth.uid() = author);

-- Policy: Users can delete their own posts
CREATE POLICY "Users can delete own posts" ON public.posts
    FOR DELETE USING (auth.uid() = author);

-- Grant permissions
GRANT ALL ON public.posts TO authenticated;
GRANT SELECT ON public.posts TO anon;